[config]
schemaVersion = "0.0.1"

[package]
namespace = "deca"
name = "Bloodstone"
versionNumber = "0.2.2"
description = "Plugin framework and general utilities for V Rising mods."
websiteUrl = "https://github.com/decaprime/Bloodstone"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[build]
icon = "./icon.png"
readme = "./README-TS.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]

[publish.categories]
v-rising = ["gloomrot-update", "mods", "server", "client"]
