[config]
schemaVersion = "0.0.1"

[package]
namespace = "deca"
name = "Bloodstone"
versionNumber = "0.1.4"
description = "Plugin framework and general utilities for V Rising mods."
websiteUrl = "https://github.com/decaprime/Bloodstone"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"

[build]
icon = "./icon.png"
readme = "./README-TS.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = ""

[publish]
repository = "https://v-rising.thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server", "client"]
